//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDetail
    {
        public int ID { get; set; }
        public int Folder_Id { get; set; }
        public string File_Names { get; set; }
        public string File_Extention { get; set; }
        public int File_Status { get; set; }
    
        public virtual FolderDetail FolderDetail { get; set; }
    }
}
