//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FolderDetail()
        {
            this.FileDetails = new HashSet<FileDetail>();
        }
    
        public int ID { get; set; }
        public string Folder_Name { get; set; }
        public string File_Count { get; set; }
        public string Folder_Count { get; set; }
        public string Parent_Folder { get; set; }
        public string Orignal_Location { get; set; }
        public int Watch_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileDetail> FileDetails { get; set; }
    }
}
